name = "LangevinIntegratorsPlumedExt"
uuid = "9b04c4b2-6a00-4512-bc48-850cc1ef78e0"
authors = ["Hadrien <hadrien.vroylandt@sorbonne-universite.fr>"]
version = "0.1.0"

[deps]
LangevinIntegrators = "563ade2f-8390-447b-b9b3-bcdc9d7fe8e5"
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
julia = ">= 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
