name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: /usr/local/lib
    steps:
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.local/include
            ~/.local/lib
          key: global-${{ runner.os }}-${{ matrix.plumed_version }}
      - uses: actions/checkout@v2
        with:
          repository: plumed/plumed2
          path: plumed
          ref: ${{ matrix.plumed_version }}
      - name: Build Plumed ${{ matrix.plumed_version }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd plumed
          ./configure --prefix=$HOME/.local/
          make -j 4
          make install
          cd ..
      - name: Plumed ${{ matrix.plumed_version }} location
        run: |
          sudo cp -ar $HOME/.local/lib/. /usr/local/lib
          sudo cp -ar $HOME/.local/include/. /usr/local/include
          ls /usr/local/lib
          echo $LD_LIBRARY_PATH
          ldd /usr/local/lib/libplumed.so
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - run: pip install numpy scipy
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.develop(PackageSpec(path=joinpath(pwd(), "plumed_extension/"))) ; Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          #DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
